// <auto-generated />
namespace MyApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ToDolist0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ToDolist0));
        
        string IMigrationMetadata.Id
        {
            get { return "201905282303482_ToDolist0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
